### ISSUE TITLE
Nasıl Çalışır

### ISSUE THREAD

**Issue by ibrahim-demirci** [ZagorTenay/Multi-threaded-HTTP-Server#1]
Hocam merhaba sunucuyu nasıl çalıştırırım. Nasıl denemeler yapabilirim acaba

**Comment by ibrahim-demirci** [comment]
gcc code.c -lpthread  -o code
./code

şeklinde çalıştırdım daha sonra tarayıcıdan localhost:7577 şeklinde girdim.  Elinize sağlık burada herhangi  bir html sayfasını nasıl geri döndürebilirim acaba

**Comment by ibrahim-demirci** [comment]
#define PATH "/home/fts/Masaüstü/mutli-threaded-web-server"  burayı index.html bulunduğu path olarak ayarladım. Halloldu :)

**Comment by ozgurhepsag** [comment]
Bu ödevi yapalı 4 yıl oluyor. Bana da iyi bir hatırlatma oldu. Kolay gelsin.
